name: Framework DS CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-multi_os:
    name: Build sur ${{ matrix.os }} (Clang/MSVC)
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      # 1. Récupération du code source
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      # 2. Installation de CMake et Ninja (Accélérateur de build multiplateforme)
      - name: Configuration de CMake
        uses: lukka/get-cmake@latest

      # 5. Étape de génération des fichiers de build CMake
      - name: Configuration du Build avec CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      # 6. Compilation globale de ds_arena, libds et main
      - name: Compilation du Framework (-O3 Release)
        run: cmake --build build --config Release

